import { motion } from "framer-motion";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Shield } from "lucide-react";

export default function Privacy() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />

      <main className="flex-1">
        <section className="py-14 md:py-20 bg-card/50 border-b border-border/50">
          <div className="container mx-auto px-4 md:px-6">
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="max-w-3xl"
            >
              <div className="flex items-center gap-2 mb-3">
                <Shield className="w-5 h-5 text-primary" />
                <p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">
                  Legal
                </p>
              </div>
              <h1 className="font-serif text-4xl md:text-5xl font-bold text-foreground tracking-tight leading-[1.05]">
                Privacy Policy
              </h1>
              <p className="text-muted-foreground text-lg mt-4 leading-relaxed">
                Last updated: May 2026
              </p>
            </motion.div>
          </div>
        </section>

        <section className="container mx-auto px-4 md:px-6 py-14 md:py-20">
          <div className="max-w-3xl mx-auto space-y-10">
            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                1. Information we collect
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                South Spice does not collect personal information. The only data
                stored is what you choose to save on your own device through your
                browser's localStorage: saved recipes, pantry selections, meal
                plans, and personal cooking notes. This data never leaves your
                device and is not transmitted to any server.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                2. How we use information
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                Local data is used solely to provide app functionality, such
                as remembering your saved recipes or displaying your meal plan
                across visits. We do not analyze, sell, or share this data.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                3. Cookies and tracking
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                We do not use cookies for tracking or advertising. We do not
                embed third-party analytics, advertising scripts, or social
                media trackers. If you subscribe to our newsletter via a
                third-party service, their privacy policy applies to that
                interaction.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                4. Third-party services
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                Recipe images are generated by AI and served from our own
                hosting. We do not rely on external image hosts that might
                track you. Our only external integration is an optional
                newsletter subscription form, which is handled by the
                subscription service you choose to use.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                5. Data retention and deletion
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                Since all data is stored locally on your device, you control it
                completely. Clearing your browser data or site storage will
                remove all saved recipes, pantry selections, meal plans, and
                cooking notes. We have no ability to recover deleted data.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                6. Children's privacy
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                South Spice does not knowingly collect any information from
                children under 13. The site is a general-audience recipe
                resource with no age-restricted content.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                7. Changes to this policy
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                We may update this Privacy Policy from time to time. Any
                changes will be posted on this page with an updated date.
                Continued use of the site after changes constitutes
                acceptance of the revised policy.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-xl font-semibold mb-3">
                8. Contact us
              </h2>
              <p className="text-foreground/85 leading-relaxed">
                If you have questions about this Privacy Policy, please reach
                out through our{" "}
                <a href="/contact" className="text-primary hover:underline underline-offset-4">
                  Contact page
                </a>
                .
              </p>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
